name: Deploy News Chatbot

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm list
      
    - name: Run tests
      run: npm test
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Install AWS CDK
      run: npm install -g aws-cdk
      
    - name: CDK Bootstrap (if needed)
      run: cdk bootstrap --app "npx ts-node src/news-chatbot-main.ts"
      continue-on-error: true
      
    - name: Deploy to AWS
      run: |
        export PERPLEXITY_API_KEY="${{ secrets.PERPLEXITY_API_KEY }}"
        cdk deploy NewsChatbotStack --app "npx ts-node src/news-chatbot-main.ts" --require-approval never
      
    - name: Output deployment info
      run: |
        echo "Deployment completed successfully!"
        echo "API Gateway URL will be shown in the CDK outputs above"